# dataset path
Dataset_input_folder: /home/leidi/Data/dataset_test/ApolloScape_test

# output path
Dataset_output_folder: /home/leidi/Data/dataset_test/ApolloScape_test_20220218

# Source dataset style:
# YUNCE_SEGMENT_COCO, YUNCE_SEGMENT_COCO_ONE_IMAGE, HUAWEIYUN_SEGMENT, CVAT_COCO2017, HY_VAL,
# SJT, MYXB, HY_HIGHWAY,
# YOLO, COCO2017, BDD100K, TT100K, CCTSDB, LISA, KITTI, APOLLOSCAPE_LANE_SEGMENT
# NO: cityscapes
Source_dataset_style: APOLLOSCAPE_LANE_SEGMENT

# Target dataset style: COCO2017, CITYSCAPES, CITYSCAPES_VAL, CVAT_IMAGE_1_1, YOLO
Target_dataset_style: COCO2017

# images or labels need to rename prefix
File_prefix: "test"

# name delimiter(cityscapes need: "@")
File_prefix_delimiter: "@"

# (train, val, test, redund)
Target_dataset_divide_proportion: 0.8,0.1,0.1,0

# check target annotations
Target_dataset_check_annotations_count: 100

# check target annotations show annotations as mask
Target_dataset_check_annotations_output_as_mask: True

# segmentation_to_box, box_to_segmentation
Need_convert: segmentation_to_box

# Task and class config, select only one.
# Detection, Semantic_segmentation, Instance_segmentation, Keypoints
Task_and_class_config:
  # Detection:
  #   Source_dataset_class_file_path: Clean_up/data/segmentation/segment_classes_apolloscape_lane_segmentation_38_classes.names
  #   Modify_class_file_path:
  #   Target_each_class_object_pixel_limit_file_path:
  Semantic_segmentation:
    Source_dataset_class_file_path: Clean_up/data/segmentation/segment_classes_apolloscape_lane_segmentation_38_classes.names
    Modify_class_file_path:
    Target_each_class_object_pixel_limit_file_path:
  # Instance_segmentation:
  #   Source_dataset_class_file_path: Clean_up/data/segmentation/segment_classes_apolloscape_lane_segmentation_38_classes.names
  #   Modify_class_file_path:
  #   Target_each_class_object_pixel_limit_file_path:
  # Keypoints:
  #   Source_dataset_class_file_path: Clean_up/data/segmentation/segment_classes_huaweiyun_segmentation_183_classes_20211116.names
  #   Modify_class_file_path: Clean_up/data/segmentation/segment_classes_huaweiyun_segmentation_183_classes_to_3_classes.txt
  #   Target_each_class_object_pixel_limit_file_path:

# progress debug
debug: False
