# dataset path
Dataset_input_folder: /mnt/data_1/Dataset/Temp/yunce_parking_2_classes_coco2017

# output path
Dataset_output_folder: /mnt/data_1/Dataset/Temp/yunce_parking_2_classes_coco2017_20220107

# Source dataset style: cityscapes, COCO2017, huaweiyun_segment, bdd100k, apolloscape_lane_segment, hy_val, cvat_coco2017, yunce_segment_coco, yunce_segment_coco_one_image
Source_dataset_style: COCO2017

# Target dataset style: cityscapes, COCO2017, cityscapes_val, cvat_image_1_1
Target_dataset_style: COCO2017

# images or labels need to rename prefix
File_prefix: yunce

# name delimiter(cityscapes need: "@")
File_prefix_delimiter: "@"

# (train, val, test, redund)
Target_dataset_divide_proportion: 0.9,0.05,0.05,0

# check target annotations
Target_dataset_check_annotations_count: 100

# check target annotations show annotations as mask
Target_dataset_check_annotations_output_as_mask: True

# progress debug
debug: False

# dataset style: Detection, Instance_segmentation, Multi_task, Semantic_segmentation
Dataset_style: Detection

# Task and class config
Task_and_class_config:
  Task_1:
    Style: "Detection"
    Source_dataset_class_file_path: "/home/leidi/hy_program/2D_Dataset_clean/Instance_segmentation_dataset_clean_up/data/segment_classes_yunce_segmentation_184_classes_20211116.names"
    Modify_class_file_path: "/home/leidi/hy_program/2D_Dataset_clean/Instance_segmentation_dataset_clean_up/data/segment_classes_yunce_segmentation_184_classes_include_infer_to_2_classes_parking_20211231.txt"
