# dataset path
Dataset_input_folder: /mnt/data_1/Dataset/dataset_temp/bdd100k_images_annotations_test

# output path
Dataset_output_folder: /mnt/data_1/Dataset/dataset_temp/bdd100k_images_annotations_test_20220214

# Source dataset style:
# COCO2017, YUNCE_SEGMENT_COCO, YUNCE_SEGMENT_COCO_ONE_IMAGE, HUAWEIYUN_SEGMENT, HY_VAL, BDD100K

# NO: cityscapes, apolloscape_lane_segment, cvat_coco2017
# PASCAL_VOC, KITTI, YOLO, TT100K, LISA, CCTSDB, SJT, MYXB, HY_HIGHWAY(小写)
Source_dataset_style: BDD100K

# Target dataset style: COCO2017, CITYSCAPES, CITYSCAPES_VAL, CVAT_IMAGE_1_1

# NO: pascal_voc, yolo
Target_dataset_style: CITYSCAPES

# images or labels need to rename prefix
File_prefix: test

# name delimiter(cityscapes need: "@")
File_prefix_delimiter: "@"

# (train, val, test, redund)
Target_dataset_divide_proportion: 0.8,0.1,0.1,0

# check target annotations
Target_dataset_check_annotations_count: 100

# check target annotations show annotations as mask
Target_dataset_check_annotations_output_as_mask: True

# Task and class config
Task_and_class_config:
  # Detection, Semantic_segmentation, Instance_segmentation, Keypoints
  # Detection:
  #   Source_dataset_class_file_path: Clean_up/data/segment_classes_yunce_segmentation_184_classes_no_infer_20211130.names
  #   Modify_class_file_path: Clean_up/data/segment_classes_yunce_segmentation_184_classes_include_infer_to_road_lane_parkingline_parking_20211116.txt
  #   Target_each_class_object_pixel_limit_file_path:
  #   Need_convert: False
  Semantic_segmentation:
    Source_dataset_class_file_path: Clean_up/data/segment_classes_bdd100k_11_classes.names
    Modify_class_file_path: Clean_up/data/segment_classes_bdd100k_11_classes_to_3_classes_road_lane.txt
    Target_each_class_object_pixel_limit_file_path:
    Need_convert: False

# progress debug
debug: False
