# dataset path
Dataset_input_folder: /mnt/data_1/Dataset/dataset_temp/yunce_parking_2_classes_coco2017

# output path
Dataset_output_folder: /mnt/data_1/Dataset/dataset_temp/yunce_parking_2_classes_coco2017_20220117

# Source dataset style: cityscapes, COCO2017, huaweiyun_segment, bdd100k, apolloscape_lane_segment, hy_val, cvat_coco2017, yunce_segment_coco, yunce_segment_coco_one_image
Source_dataset_style: COCO2017

# Target dataset style: cityscapes, COCO2017, cityscapes_val, cvat_image_1_1
Target_dataset_style: COCO2017

# images or labels need to rename prefix
File_prefix: yunce

# name delimiter(cityscapes need: "@")
File_prefix_delimiter: "@"

# (train, val, test, redund)
Target_dataset_divide_proportion: 0.8,0.1,0.1,0

# check target annotations
Target_dataset_check_annotations_count: 100

# check target annotations show annotations as mask
Target_dataset_check_annotations_output_as_mask: True

# dataset style: Detection, Semantic_segmentation, Instance_segmentation, Multi_task
Dataset_style: Detection

# Task and class config
Task_and_class_config:
  # Detection, Semantic_segmentation, Instance_segmentation, Keypoint
  Detection:
    Source_dataset_class_file_path: /mnt/data_1/hy_program/2D_Dataset_clean/Clean_up/data/test_2_classes.name
    Modify_class_file_path: /mnt/data_1/hy_program/2D_Dataset_clean/Clean_up/data/test_2_classes_modify.txt
    Target_each_class_object_pixel_limit_file_path: 

# progress debug
debug: False
