input_folder: /mnt/data_1/Dataset/dataset_sample/whu_20211123

output_folder: /mnt/data_1/Dataset/dataset_sample/whu_20211123_4_image_concate

concate_num: 4

# images or labels need to rename prefix
File_prefix: "test"

# name delimiter(cityscapes need: "@")
File_prefix_delimiter: "@"
